-- Enterprise AI Copilot Gateway — baseline schema.
-- Portable DDL: runs on PostgreSQL and on H2 in PostgreSQL compatibility mode.

CREATE TABLE chat_threads (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    thread_id      VARCHAR(64)  NOT NULL,
    tenant_id      VARCHAR(64)  NOT NULL,
    user_sub       VARCHAR(128) NOT NULL,
    app_id         VARCHAR(64)  NOT NULL,
    title          VARCHAR(200),
    created_at     TIMESTAMP    NOT NULL,
    last_active_at TIMESTAMP    NOT NULL
);

CREATE UNIQUE INDEX idx_thread_key ON chat_threads (thread_id);
CREATE INDEX idx_thread_owner ON chat_threads (tenant_id, user_sub);

CREATE TABLE chat_messages (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    thread_id  VARCHAR(64) NOT NULL,
    role       VARCHAR(16) NOT NULL,
    content    TEXT        NOT NULL,
    created_at TIMESTAMP   NOT NULL
);

CREATE INDEX idx_message_thread ON chat_messages (thread_id, id);

CREATE TABLE audit_records (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trace_id     VARCHAR(64)  NOT NULL,
    user_sub     VARCHAR(128) NOT NULL,
    tenant_id    VARCHAR(64)  NOT NULL,
    app_id       VARCHAR(64)  NOT NULL,
    thread_id    VARCHAR(64),
    question     TEXT         NOT NULL,
    context_hash VARCHAR(64)  NOT NULL,
    answer       TEXT,
    model        VARCHAR(128),
    status       VARCHAR(16)  NOT NULL,
    error_code   VARCHAR(64),
    latency_ms   BIGINT,
    created_at   TIMESTAMP    NOT NULL
);

CREATE INDEX idx_audit_tenant_created ON audit_records (tenant_id, created_at);
CREATE INDEX idx_audit_trace ON audit_records (trace_id);
CREATE INDEX idx_audit_thread ON audit_records (thread_id);
